---
- name: Installing s/w packages
  hosts: all
  tasks: 
   - name: Install s/w
     apt:
      name: "{{item.a}}"
      state: "{{item.b}}"
      update_cache: "{{item.c}}"
     with_items: 
      - {a: tree,b: present,c: no}
      - {a: apache2,b: latest,c: no}
      - {a: git,b: present,c: yes}
