---
- name: Implementing the handlers
  hosts: all
  tasks:
   - name: Install apache2
     apt:
      name: apache2
      state: present
   - name: edit index.html file
     copy:
      content: "IntelliQ\n"
      dest: /var/www/html/index.html
     notify: Restart apache2
  handlers:
   - name: Restart apache2
     service: 
       name: apache2
       state: restarted
...
